name: Call Reusable Workflow

on:
  push:
    branches:
      - main

jobs:
  call-reusable:
    uses: ./.github/workflows/reusable.yml
    with:
      name: bishalmurmu
    secrets:
      MY_SECRET: This  is secrete for now

  print:
    runs-on: ubuntu-latest
    needs: call
    steps:
      - run: echo "${{ needs.call-reusable.outputs.message }}"
